### PR TITLE
Make Program.cs top level and use Factory test

### PR DESCRIPTION
**Pull request by rlnprogrammering**
**Addings in this PR**
- Refactor Program.cs to be top level
- Add test to the github build/test .yml file
- Use Factory for testing

### CODE REVIEW

**Review by Noerklit — APPROVED** [review]
Clean as hell.

**Review by JacobPaerre — APPROVED** [review]
LGTM 👍

**Review by DanielSMillard — APPROVED** [review]
Bred Ymer👌

**Review by frederiklr99 — APPROVED** [review]
Ser meget flot ud

**Pull request merged**
